spring.application.name=API-Gateway
#Eureka service UrL for Microservice Registration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
server.port=8080
spring.main.web-application-type=reactive

#Route to the User-Service
spring.cloud.gateway.server.webflux.routes[0].id=User-Service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/user-service/v1/**


#To ignore the prefix from the request like each service can have api/** so ignore it
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

#Route to the Product-Service
spring.cloud.gateway.server.webflux.routes[1].id=Product-Service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/product-service/v1/**

#Route to the Order-Service
spring.cloud.gateway.server.webflux.routes[2].id=Order-Service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/order/v1/**
