spring.application.name=Eureka-Server

# Change the server port for Eureka server port by default it supports 8761
server.port = 8761

#Adding Eureka server properties

eureka.client.registerWithEureka = false
eureka.client.fetchRegistry = false